import { Debug } from './scenes/interfaces';

export const debugInit: Debug = {
  Auto_Start: false,
  NN_Train_P1: false,
  Dev_Mode: false,
  Dur_Seconds: false,
  Mode_Infinity: true,
  Minutes: 1, //01234567
  Shots: 7, //7
  Dev_Zoom: 8,
  Level: 9, //0123456
  Music_Active: true,
  Ready_Sound_Active: false,
  Use_Camera: false,
  Cameras_Visible: false,
  Colliders_P_v_P: false,
  Colliders_P_v_AP: false,
  Colliders_P_v_AE: false,
  Colliders_AE_v_AE: true,
  Colliders_AE_v_AP: true,
  Colliders_AB_v_AE: false,
  Colliders_AB_v_AP: false,
  Title_Screws: true,
  Show_Helper_Keyboard: false,
  Friction_Air_Active: true,
  AE_Wrap_Screen: false,
  Wall_Jumps_Active: true,
  Default_Damage: false,
  Default_Hitback: false,
  Player_ID_Visible: true,
  Chars_Colored: false,
  Health_Inverted: false,
  Matrices_Always: false,
  Console_Log_Buttons: false,
  Console_Log_Connected: false,
  Update_Loops_Skip: 2, // 012
  Load_Time_Extra: true,
  Allow_Koopas: true,
  Allow_Chez: true,
  Allow_BlackChez: false,
  Typed_Loading_Text: false,
  Chomps_SlowMo: false,
  Chomp_Explosion: true,
  Char_Override: false,
  Char_Override_ID: 3,
  Bullets_Allow_Groups: true,
  Trophies_On_Shots: false,
  Trophies_Always: false,
  Inst_Replay: 0,
  Chomp_Velocities: true,
  Replay_FastSlow: false,
  Gravity_Light: false,
  NN_Help_Screen: true,
  NN_Help_Centerize: false,
  NN_Help_Pit: true,
  NN_Help_Wall: true,
  Music_Track: 0, // 0123
  Flower_On_Init: true,
  Flower_Rapid_Fire: false,
  Flower_Full_Screen: false,
  Flower_Gravity: true,
  Flower_Bounce_Wall: false,
  Flower_1000_Balls: false,
  Flower_ShootRndAmt: 1,
  Flower_HighTrajectory: 0,
  BulletBill_Active: false,
};

export const debugMax: Debug = {
  Level: 8, //0123456
  Dur_Seconds: true,
  Mode_Infinity: true,
  Shots: 15,
  Auto_Start: true,
  Minutes: 15, //01234567
  Music_Active: true,
  Music_Track: 4, // 012
  Ready_Sound_Active: true,
  Use_Camera: true,
  Cameras_Visible: false,
  Colliders_P_v_P: false,
  Colliders_P_v_AP: false,
  Colliders_P_v_AE: false,
  Colliders_AE_v_AE: true,
  Colliders_AE_v_AP: true,
  Colliders_AB_v_AE: false,
  Colliders_AB_v_AP: false,
  Friction_Air_Active: true,
  Chomp_Velocities: true,
  Title_Screws: true,
  AE_Wrap_Screen: false,
  Wall_Jumps_Active: true,
  Default_Damage: false,
  Default_Hitback: false,
  Player_ID_Visible: true,
  Chars_Colored: true,
  Health_Inverted: false,
  Matrices_Always: false,
  Console_Log_Buttons: false,
  Console_Log_Connected: false,
  Update_Loops_Skip: 2, // 012
  Load_Time_Extra: true,
  Allow_Koopas: true,
  Allow_BlackChez: true,
  Allow_Chez: false,
  Chomps_SlowMo: true,
  Typed_Loading_Text: false,
  Dev_Mode: true,
  Dev_Zoom: 10,
  Show_Helper_Keyboard: true,
  Char_Override: true,
  Char_Override_ID: 8,
  Bullets_Allow_Groups: true,
  Trophies_On_Shots: true,
  Trophies_Always: true,
  NN_Train_P1: true,
  NN_Help_Screen: true, // 012
  NN_Help_Centerize: true,
  NN_Help_Pit: true,
  NN_Help_Wall: true,
  Inst_Replay: 3,
  Chomp_Explosion: true,
  Replay_FastSlow: true,
  Gravity_Light: false,
  Flower_Rapid_Fire: false,
  Flower_On_Init: true,
  Flower_Full_Screen: false,
  Flower_Gravity: true,
  Flower_Bounce_Wall: false,
  Flower_1000_Balls: true,
  Flower_ShootRndAmt: 4,
  Flower_HighTrajectory: 2,
  BulletBill_Active: true,
};

// TRUE means SHOWN ON MAIN PAGE
export const showOptionOnMainScreenInit: Debug = {
  NN_Train_P1: true,
  Level: 1, //0123456
  Mode_Infinity: true,
  Dur_Seconds: false,
  Shots: 0,
  Minutes: 1, //01234567
  Music_Active: false,
  Auto_Start: false,
  Ready_Sound_Active: false,
  Use_Camera: false,
  Show_Helper_Keyboard: false,
  Cameras_Visible: false,
  Colliders_P_v_P: false,
  Colliders_P_v_AP: false,
  Colliders_P_v_AE: false,
  Chomp_Velocities: false,
  Colliders_AE_v_AE: false,
  Colliders_AE_v_AP: false,
  Colliders_AB_v_AE: false,
  Colliders_AB_v_AP: false,
  Friction_Air_Active: false,
  AE_Wrap_Screen: false,
  Wall_Jumps_Active: false,
  Default_Damage: false,
  Default_Hitback: false,
  Player_ID_Visible: false,
  Chars_Colored: false,
  Title_Screws: false,
  Health_Inverted: false,
  Matrices_Always: false,
  Console_Log_Buttons: false,
  Console_Log_Connected: false,
  Update_Loops_Skip: 0, // 012
  Load_Time_Extra: false,
  Allow_Koopas: false,
  Allow_BlackChez: false,
  Allow_Chez: false,
  Chomps_SlowMo: false,
  Typed_Loading_Text: false,
  Dev_Mode: false,
  Dev_Zoom: 0,
  Char_Override: false,
  NN_Help_Screen: false,
  NN_Help_Centerize: false,
  NN_Help_Pit: false,
  NN_Help_Wall: false,
  Char_Override_ID: 0,
  Bullets_Allow_Groups: false,
  Trophies_On_Shots: false,
  Chomp_Explosion: false,
  Trophies_Always: false,
  Inst_Replay: 1,
  Replay_FastSlow: false,
  Gravity_Light: false,
  Music_Track: 1, // 012
  Flower_On_Init: false,
  Flower_Rapid_Fire: false,
  Flower_Full_Screen: false,
  Flower_Gravity: false,
  Flower_Bounce_Wall: false,
  Flower_1000_Balls: false,
  Flower_ShootRndAmt: 0,
  Flower_HighTrajectory: 0,
  BulletBill_Active: false,
};
