import { Debug } from './scenes/types';

export const debugMax: Debug = {
  Nintendo_Sprites: true,
  Auto_Restart: false,
  NN_Reset_Evolving: false,
  NN_Train_Static: true,
  NN_Train_Evolving: true,
  Super_Speed: true,
  NN_Brand_New: false,
  Stage: 10, //0123456
  Dur_Seconds: true,
  Mode_Infinity: true,
  Shots: 15,
  Auto_Start: true,
  Minutes: 15, //01234567
  Music_Active: true,
  Game_Music: 4, // 012
  Ready_Sound_Active: true,
  Use_Camera: true,
  Cameras_Visible: true,
  Colliders_P_v_P: false,
  Colliders_P_v_AP: false,
  Colliders_P_v_AE: false,
  Colliders_AE_v_AE: true,
  Colliders_AE_v_AP: true,
  Colliders_AB_v_AE: false,
  Colliders_AB_v_AP: false,
  Friction_Air_Active: true,
  Chomp_Velocities: true,
  Title_Screws: true,
  AE_Wrap_Screen: false,
  Wall_Jumps_Active: true,
  Default_Damage: false,
  Default_Hitback: false,
  Player_ID_Visible: true,
  Chars_Colored: true,
  Health_Inverted: false,
  Matrices_Always: false,
  Console_Log_Buttons: false,
  Console_Log_Connected: false,
  Update_Loops_Skip: 2, // 012
  Load_Time_Extra: true,
  Allow_Shell_Chars: true,
  Allow_BlackChez: true,
  Allow_Chez: false,
  Allow_SlowMo: true,

  Dev_Mode: true,
  Dev_Zoom: 10,
  Show_Helper_Keyboard: true,
  Char_Override: true,
  Char_Override_ID: 8,
  Bullets_Allow_Groups: true,
  Trophies_On_Shots: true,
  Trophies_Always: true,
  Simple_Stage: true,
  NN_Help_Screen: true, // 012
  NN_Help_Centerize: true,
  NN_Help_Pit: true,
  NN_Help_Wall: true,
  Inst_Replay: 3,
  Chomp_Explosion: true,
  Replay_FastSlow: true,
  Flower_Rapid_Fire: false,
  Flower_On_Init: true,
  Flower_Full_Screen: false,
  Flower_Gravity: true,
  Flower_Bounce_Wall: false,
  Flower_1000_Balls: true,
  Flower_ShootRndAmt: 4,
  Flower_HighTrajectory: 2,
  Allow_Mobile: true,
};
