import { Debug } from './scenes/types';

export const debugInit: Debug = {
  Mode_Infinity: false,
  Minutes: 2, //01234567
  Shots: 8, //7
  Nintendo_Sprites: false,
  Pixel_Graphics: false,
  Pixel_Density: 2,
  Allow_Mobile: true,
  Auto_Start: false,
  Auto_Restart: false,
  Super_Speed: false,
  NN_Train_Static: false,
  NN_Train_Evolving: true,
  NN_Reset_Evolving: true,
  NN_Brand_New: false,

  NN_Help_Screen: true,
  NN_Help_Centerize: false,
  NN_Help_Pit: true,
  NN_Help_Wall: true,
  Simple_Stage: false,

  Dev_Mode: false,

  Dur_Seconds: false,
  Dev_Zoom: 8,
  Stage: 12, // 0 - 12 inclusive
  Music_Active: true,
  Ready_Sound_Active: true,
  Use_Camera: true,
  Cameras_Visible: false,
  Colliders_P_v_P: false,
  Colliders_P_v_AP: false,
  Colliders_P_v_AE: false,
  Colliders_AE_v_AE: true,
  Colliders_AE_v_AP: true,
  Colliders_AB_v_AE: false,
  Colliders_AB_v_AP: false,
  Colliders_P_v_BB: false,
  Title_Screws: true,
  Show_Helper_Keyboard: true,
  Friction_Air_Active: true,
  AE_Wrap_Screen: false,
  Wall_Jumps_Active: true,
  Default_Damage: false,
  Default_Hitback: false,
  Player_ID_Visible: true,
  Chars_Colored: false,
  Health_Inverted: false,
  Matrices_Always: false,
  Console_Log_Buttons: false,
  Console_Log_Connected: false,
  Update_Loops_Skip: 2, // 012
  Load_Time_Extra: false,
  Allow_Shell_Chars: true,
  Allow_Chez: true,
  Allow_BlackChez: false,

  Allow_SlowMo: true,
  Chomp_Explosion: true,
  Chomp_Velocities: true,
  Char_Override: false,
  Char_Override_ID: 0,
  Bullets_Allow_Groups: true,
  Trophies_On_Shots: false,
  Trophies_Always: false,
  Inst_Replay: 2,
  Replay_FastSlow: false,
  Game_Music: 0, // 0123
  Flower_On_Init: false,
  Flower_Rapid_Fire: false,
  Flower_Full_Screen: false,
  Flower_Gravity: true,
  Flower_Bounce_Wall: false,
  Flower_1000_Balls: false,
  Flower_ShootRndAmt: 0,
  Flower_HighTrajectory: 1,
};
