import { Debug } from './scenes/interfaces';

export const debugInit: Debug = {
  auto_start: false,
  nn_train_p1: false,
  dev_mode: false,
  dur_seconds: false,
  mode_infinity: false,
  minutes: 1, //01234567
  shots: 7, //7
  dev_zoom: 8,
  level: 9, //0123456
  music_active: true,
  ready_sound_active: false,
  use_camera: true,
  cameras_visible: false,
  colliders_P_v_P: false,
  colliders_p_v_ap: false,
  colliders_p_v_ae: false,
  colliders_ae_v_ae: true,
  colliders_ae_v_ap: true,
  colliders_ab_v_ae: false,
  colliders_ab_v_ap: false,
  super_mario_bros_screws: true,
  show_helper_keyboard: false,
  friction_air_active: true,
  ae_wrap_screen: false,
  wall_jumps_active: true,
  default_damage: false,
  default_hitback: false,
  player_id_visible: true,
  chars_colored: false,
  health_inverted: false,
  matrices_always: false,
  console_log_buttons: false,
  console_log_connected: false,
  update_loops_num_skip: 2, // 012
  load_time_extra: true,
  allow_koopas: true,
  allow_chez: true,
  allow_black_chez: false,
  typed_loading_text: false,
  chomps_slow_mo: false,
  chomp_explosions: true,
  char_override: false,
  char_override_id: 3,
  bullets_allow_groups: true,
  bullets_fullscreen: false,
  tropies_on_shots: false,
  trophies_always: false,
  inst_replay: 0,
  chomp_velocities: true,
  replay_fast_slow: false,
  gravity_light: false,
  nn_help_screen: true,
  nn_help_centerize: false,
  nn_help_pit: true,
  nn_help_wall: true,
  music_track: 0, // 0123
  flower_on_init: true,
  flower_rapid_fire: false,
  flower_full_screen: false,
  flower_gravity: true,
  flower_bounce_wall: true,
  flower_1000_balls: false,
  bullet_bill_active: false,
};

export const debugMax: Debug = {
  level: 8, //0123456
  dur_seconds: true,
  mode_infinity: true,
  shots: 15,
  auto_start: true,
  minutes: 15, //01234567
  music_active: true,
  music_track: 3, // 012
  ready_sound_active: true,
  use_camera: true,
  cameras_visible: false,
  colliders_P_v_P: false,
  colliders_p_v_ap: false,
  colliders_p_v_ae: false,
  colliders_ae_v_ae: true,
  colliders_ae_v_ap: true,
  colliders_ab_v_ae: false,
  colliders_ab_v_ap: false,
  friction_air_active: true,
  chomp_velocities: true,
  super_mario_bros_screws: true,
  ae_wrap_screen: false,
  wall_jumps_active: true,
  default_damage: false,
  default_hitback: false,
  player_id_visible: true,
  chars_colored: true,
  health_inverted: false,
  matrices_always: false,
  console_log_buttons: false,
  console_log_connected: false,
  update_loops_num_skip: 2, // 012
  load_time_extra: true,
  allow_koopas: true,
  allow_black_chez: true,
  allow_chez: false,
  chomps_slow_mo: true,
  typed_loading_text: false,
  dev_mode: true,
  dev_zoom: 10,
  show_helper_keyboard: true,
  char_override: true,
  char_override_id: 8,
  bullets_allow_groups: true,
  bullets_fullscreen: true,
  tropies_on_shots: true,
  trophies_always: true,
  nn_train_p1: true,
  nn_help_screen: true, // 012
  nn_help_centerize: true,
  nn_help_pit: true,
  nn_help_wall: true,
  inst_replay: 3,
  chomp_explosions: true,
  replay_fast_slow: true,
  gravity_light: false,
  flower_rapid_fire: true,
  flower_on_init: true,
  flower_full_screen: true,
  flower_gravity: true,
  flower_bounce_wall: true,
  flower_1000_balls: true,
  bullet_bill_active: true,
};

// TRUE means SHOWN ON MAIN PAGE
export const showOptionOnMainScreenInit: Debug = {
  nn_train_p1: true,
  level: 1, //0123456
  mode_infinity: true,
  dur_seconds: false,
  shots: 0,
  minutes: 1, //01234567
  music_active: false,
  auto_start: false,
  ready_sound_active: false,
  use_camera: false,
  show_helper_keyboard: false,
  cameras_visible: false,
  colliders_P_v_P: false,
  colliders_p_v_ap: false,
  colliders_p_v_ae: false,
  chomp_velocities: false,
  colliders_ae_v_ae: false,
  colliders_ae_v_ap: false,
  colliders_ab_v_ae: false,
  colliders_ab_v_ap: false,
  friction_air_active: false,
  ae_wrap_screen: false,
  wall_jumps_active: false,
  default_damage: false,
  default_hitback: false,
  player_id_visible: false,
  chars_colored: false,
  super_mario_bros_screws: false,
  health_inverted: false,
  matrices_always: false,
  console_log_buttons: false,
  console_log_connected: false,
  update_loops_num_skip: 0, // 012
  load_time_extra: false,
  allow_koopas: false,
  allow_black_chez: false,
  allow_chez: false,
  chomps_slow_mo: false,
  typed_loading_text: false,
  dev_mode: false,
  dev_zoom: 0,
  char_override: false,
  nn_help_screen: false,
  nn_help_centerize: false,
  nn_help_pit: false,
  nn_help_wall: false,
  char_override_id: 0,
  bullets_allow_groups: false,
  bullets_fullscreen: false,
  tropies_on_shots: false,
  chomp_explosions: false,
  trophies_always: false,
  inst_replay: 1,
  replay_fast_slow: false,
  gravity_light: false,
  music_track: 1, // 012
  flower_on_init: false,
  flower_rapid_fire: false,
  flower_full_screen: false,
  flower_gravity: false,
  flower_bounce_wall: false,
  flower_1000_balls: false,
  bullet_bill_active: false,
};
