import { Debug } from './scenes/interfaces';

export const debugInit: Debug = {
  DevMode: false,
  DevZoom: 8,
  Level: 6, //0123456
  ModeInfinity: true,
  NumShots: 7, //7
  TimeMinutes: 7, //01234567
  MusicActive: true,
  MusicTrack: 3, // 012
  ReadySoundActive: false,
  UseCamera: true,
  CamerasVisible: false,
  CollidersPvP: false,
  CollidersPvAP: false,
  CollidersPvAE: false,
  CollidersAEvAE: true,
  CollidersAEvAP: true,
  CollidersABvAE: false,
  CollidersABvAP: false,
  FrictionAirActive: true,
  AEWrapScreen: false,
  WallJumpsActive: true,
  DefaultDamage: false,
  DefaultHitback: false,
  PlayerIdVisible: true,
  CharsColored: false,
  HealthInverted: false,
  MatricesAlways: false,
  ConsoleLogButtons: false,
  ConsoleLogConnected: false,
  UpdateLoopsNumSkip: 2, // 012
  LoadTimeExtra: true,
  UseKoopas: false,
  UseChez: false,
  SlowMoExplosions: false,
  TypedLoadingText: false,
  CharOverride: false,
  CharOverrideId: 3,
  BulletsAllowGroups: true,
  BulletsFullScreen: false,
  TrophiesOnShots: false,
  TrophiesAlways: false,
  // NeuralNetworkBot: false,
  NNP1Train: false,
  NNIsLSTM: false,
  FullQualityReplay: true,
};

export const debugMax: Debug = {
  Level: 6, //0123456
  ModeInfinity: true,
  NumShots: 15,
  TimeMinutes: 15, //01234567
  MusicActive: true,
  MusicTrack: 3, // 012
  ReadySoundActive: true,
  UseCamera: true,
  CamerasVisible: false,
  CollidersPvP: false,
  CollidersPvAP: false,
  CollidersPvAE: false,
  CollidersAEvAE: true,
  CollidersAEvAP: true,
  CollidersABvAE: false,
  CollidersABvAP: false,
  FrictionAirActive: true,
  AEWrapScreen: false,
  WallJumpsActive: true,
  DefaultDamage: false,
  DefaultHitback: false,
  PlayerIdVisible: true,
  CharsColored: true,
  HealthInverted: false,
  MatricesAlways: false,
  ConsoleLogButtons: false,
  ConsoleLogConnected: false,
  UpdateLoopsNumSkip: 2, // 012
  LoadTimeExtra: true,
  UseKoopas: true,
  UseChez: false,
  SlowMoExplosions: true,
  TypedLoadingText: false,
  DevMode: true,
  DevZoom: 10,
  CharOverride: true,
  CharOverrideId: 8,
  BulletsAllowGroups: true,
  BulletsFullScreen: true,
  TrophiesOnShots: true,
  TrophiesAlways: true,
  // NeuralNetworkBot: true,
  NNP1Train: true,
  NNIsLSTM: false,
  FullQualityReplay: true,
};

// TRUE means SHOWN ON MAIN PAGE
export const mainOptionsDebugShow: Debug = {
  Level: 0, //0123456
  ModeInfinity: false,
  NumShots: 1,
  TimeMinutes: 0, //01234567
  MusicActive: false,
  MusicTrack: 1, // 012
  ReadySoundActive: false,
  UseCamera: false,
  CamerasVisible: false,
  CollidersPvP: false,
  CollidersPvAP: false,
  CollidersPvAE: false,
  CollidersAEvAE: false,
  CollidersAEvAP: false,
  CollidersABvAE: false,
  CollidersABvAP: false,
  FrictionAirActive: false,
  AEWrapScreen: false,
  WallJumpsActive: false,
  DefaultDamage: false,
  DefaultHitback: false,
  PlayerIdVisible: false,
  CharsColored: true,
  HealthInverted: false,
  MatricesAlways: false,
  ConsoleLogButtons: false,
  ConsoleLogConnected: false,
  UpdateLoopsNumSkip: 0, // 012
  LoadTimeExtra: false,
  UseKoopas: true,
  UseChez: true,
  SlowMoExplosions: false,
  TypedLoadingText: false,
  DevMode: false,
  DevZoom: 0,
  CharOverride: false,
  CharOverrideId: 0,
  BulletsAllowGroups: false,
  BulletsFullScreen: false,
  TrophiesOnShots: false,
  TrophiesAlways: false,
  // NeuralNetworkBot: false,
  NNP1Train: false,
  NNIsLSTM: false,
  FullQualityReplay: false,
};
