import { Debug } from './scenes/types';

export const debugHide: Debug = {
  Nintendo_Sprites: true,
  Force_Pixelated: false,
  Auto_Restart: false,
  NN_Reset_Evolving: false,
  NN_Train_Static: false,
  NN_Train_Evolving: false,
  Super_Speed: false,
  NN_Brand_New: false,
  NN_Help_Screen: false,
  NN_Help_Centerize: false,
  NN_Help_Pit: false,
  NN_Help_Wall: false,

  Simple_Stage: false,
  Dev_Mode: false,
  Auto_Start: false,
  Dur_Seconds: false,
  Mode_Infinity: false,
  Minutes: 0, //01234567
  Shots: 0, //7
  Dev_Zoom: 0,
  Stage: 0, // 0 - 10 inclusive
  Music_Active: false,
  Ready_Sound_Active: false,
  Use_Camera: false,
  Cameras_Visible: false,
  Colliders_P_v_P: false,
  Colliders_P_v_AP: false,
  Colliders_P_v_AE: false,
  Colliders_AE_v_AE: false,
  Colliders_AE_v_AP: false,
  Colliders_AB_v_AE: false,
  Colliders_AB_v_AP: false,
  Colliders_P_v_BB: false,
  Title_Screws: false,
  Show_Helper_Keyboard: false,
  Friction_Air_Active: false,
  AE_Wrap_Screen: false,
  Wall_Jumps_Active: false,
  Default_Damage: false,
  Default_Hitback: false,
  Player_ID_Visible: false,
  Chars_Colored: false,
  Health_Inverted: false,
  Matrices_Always: false,
  Console_Log_Buttons: false,
  Console_Log_Connected: false,
  Update_Loops_Skip: 0, // 012
  Load_Time_Extra: false,
  Allow_Shell_Chars: false,
  Allow_Chez: false,
  Allow_BlackChez: false,
  Allow_SlowMo: false,
  Chomp_Explosion: false,
  Chomp_Velocities: false,
  Char_Override: false,
  Char_Override_ID: 0,
  Bullets_Allow_Groups: false,
  Trophies_On_Shots: false,
  Trophies_Always: false,
  Inst_Replay: 0,
  Replay_FastSlow: false,
  Game_Music: 0, // 0123
  Flower_On_Init: false,
  Flower_Rapid_Fire: false,
  Flower_Full_Screen: false,
  Flower_Gravity: false,
  Flower_Bounce_Wall: false,
  Flower_1000_Balls: false,
  Flower_ShootRndAmt: 0,
  Flower_HighTrajectory: 0,
  Allow_Mobile: false,
};
